; zsh-fast-syntax-highlighting theme loosely based on monokai-8

[base]
default          = none
unknown-token    = red,underline
commandseparator = red
redirection      = red
here-string-tri  = red
here-string-text = yellow
here-string-var  = white,bold
exec-descriptor  = yellow,bold
comment          = 8,bold
correct-subtle   = none
incorrect-subtle = red,underline
subtle-separator = 12
subtle-bg        = bg:18
secondary        = ~/.config/zsh/syntax-highlighting-themes/monokai.ini
recursive-base   = none

[command-point]
reserved-word  = red
subcommand     = magenta
alias          = green
suffix-alias   = green
global-alias   = bg:blue
builtin        = cyan
function       = green
command        = green
precommand     = green
hashed-command = green
single-sq-bracket = red
double-sq-bracket = red
double-paren   = red

[paths]
path          = yellow
pathseparator = 
path-to-dir   = yellow,underline
globbing      = yellow,bold
globbing-ext  = yellow

[brackets]
paired-bracket = black,bg:white
bracket-level-1 = blue,bold
bracket-level-2 = magenta,bold
bracket-level-3 = cyan,bold

[arguments]
single-hyphen-option   = magenta
double-hyphen-option   = magenta
back-quoted-argument   = none
single-quoted-argument = yellow
double-quoted-argument = yellow
dollar-quoted-argument = yellow
optarg-string          = yellow
optarg-number          = magenta

[in-string]
back-dollar-quoted-argument           = white,bold
back-or-dollar-double-quoted-argument = white,bold

[other]
variable             = white,bold
assign               = none
assign-array-bracket = red
history-expansion    = white,bold

[math]
mathvar = none
mathnum = magenta
matherr = red,bold

[for-loop]
forvar = none
fornum = magenta
; operator
foroper = red
; separator
forsep = none

[case]
case-input       = none
case-parentheses = red
case-condition   = none